package:
  name: microbeannotator
  version: 1.0.0

source:
  git_url: https://github.com/cruizperez/MicrobeAnnotator.git

requirements:
  build:
    - python
    - setuptools
    - blast 
    - hmmer
    - ruby=2.5.1
    - parallel
    - diamond
    - sword
    - seaborn
    - biopython
    - pywget

  run:
    - python

test:
  commands:
    - microbeannotator --help
    - microbeannotator_db_builder --help

about:
  home: https://github.com/cruizperez/MicrobeAnnotator
  license: Artistic License 2.0
  license_file: LICENSE

extra:
  notes: Databases required. Please run the "microbeannotator_db_builder" script.
