{% set name = "microbeannotator" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 075b18602261f89a8215d652a7b3887309955dc6a82bdc48490e517d7f3ac6da

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - setuptools
  host:
    - pip
    - python ==3.7.5
    - setuptools
  run:
    - attrs ==20.3.0
    - biopython ==1.78
    - blast ==2.11.0
    - diamond ==2.0.9
    - matplotlib ==3.4.1
    - pandas ==1.2.4
    - psutil ==5.8.0
    - python ==3.7.5
    - pywget ==3.2
    - requests ==2.25.1
    - seaborn ==0.11.1
    - sword ==1.0.4

test:
  commands:
    - microbeannotator --help
    - microbeannotator_db_builder --help

about:
  home: "https://github.com/cruizperez/MicrobeAnnotator"
  license: Artistic Licence 2.0
  license_file: LICENSE
  summary: "A user friendly microbe genome annotation tool"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cruizperez
